import type { Product, InventoryLevel } from '@/lib/types'

export const mockProducts: Product[] = [
  // Canned Goods
  {
    id: 'prod_001',
    sku: 'SARD-155G',
    name: 'Lucky Sardines',
    description: 'Premium sardines in tomato sauce',
    categoryId: 'cat_001',
    supplierId: 'sup_001',
    variants: [
      { id: 'var_001a', name: 'Regular', priceAdjustment: 0 },
      { id: 'var_001b', name: 'Spicy', priceAdjustment: 2 },
    ],
    costPrice: 18,
    wholesalePrice: 21,
    retailPrice: 25,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_002',
    sku: 'CORN-150G',
    name: 'Purefoods Corned Beef',
    description: 'Classic corned beef',
    categoryId: 'cat_001',
    supplierId: 'sup_001',
    variants: [],
    costPrice: 35,
    wholesalePrice: 42,
    retailPrice: 48,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  // Beverages
  {
    id: 'prod_003',
    sku: 'COKE-330ML',
    name: 'Coca-Cola',
    description: 'Classic Coca-Cola',
    categoryId: 'cat_002',
    supplierId: 'sup_005',
    variants: [
      { id: 'var_003a', name: 'Regular', priceAdjustment: 0 },
      { id: 'var_003b', name: 'Zero Sugar', priceAdjustment: 0 },
    ],
    costPrice: 22,
    wholesalePrice: 26,
    retailPrice: 30,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_004',
    sku: 'SPRITE-330ML',
    name: 'Sprite',
    description: 'Lemon-lime soda',
    categoryId: 'cat_002',
    supplierId: 'sup_005',
    variants: [],
    costPrice: 22,
    wholesalePrice: 26,
    retailPrice: 30,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_005',
    sku: 'C2-500ML',
    name: 'C2 Green Tea',
    description: 'Refreshing green tea',
    categoryId: 'cat_002',
    supplierId: 'sup_005',
    variants: [
      { id: 'var_005a', name: 'Apple', priceAdjustment: 0 },
      { id: 'var_005b', name: 'Lemon', priceAdjustment: 0 },
    ],
    costPrice: 18,
    wholesalePrice: 21,
    retailPrice: 25,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  // Snacks
  {
    id: 'prod_006',
    sku: 'PIATTOS-85G',
    name: 'Piattos',
    description: 'Crispy potato chips',
    categoryId: 'cat_003',
    supplierId: 'sup_003',
    variants: [
      { id: 'var_006a', name: 'Cheese', priceAdjustment: 0 },
      { id: 'var_006b', name: 'Sour Cream', priceAdjustment: 0 },
      { id: 'var_006c', name: 'BBQ', priceAdjustment: 0 },
    ],
    costPrice: 28,
    wholesalePrice: 33,
    retailPrice: 38,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_007',
    sku: 'NOVA-78G',
    name: 'Nova Chips',
    description: 'Multi-grain snack chips',
    categoryId: 'cat_003',
    supplierId: 'sup_003',
    variants: [
      { id: 'var_007a', name: 'Country Cheddar', priceAdjustment: 0 },
      { id: 'var_007b', name: 'Sweet Chili', priceAdjustment: 0 },
    ],
    costPrice: 25,
    wholesalePrice: 30,
    retailPrice: 35,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_008',
    sku: 'SKYFLAKES-25G',
    name: 'Skyflakes Crackers',
    description: 'Classic crackers',
    categoryId: 'cat_003',
    supplierId: 'sup_003',
    variants: [],
    costPrice: 8,
    wholesalePrice: 10,
    retailPrice: 12,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  // Personal Care
  {
    id: 'prod_009',
    sku: 'SAFEGUARD-135G',
    name: 'Safeguard Soap',
    description: 'Antibacterial soap',
    categoryId: 'cat_004',
    supplierId: 'sup_004',
    variants: [
      { id: 'var_009a', name: 'Pure White', priceAdjustment: 0 },
      { id: 'var_009b', name: 'Fresh Green', priceAdjustment: 0 },
    ],
    costPrice: 32,
    wholesalePrice: 39,
    retailPrice: 45,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_010',
    sku: 'PALMOLIVE-180ML',
    name: 'Palmolive Shampoo',
    description: 'Nourishing shampoo',
    categoryId: 'cat_004',
    supplierId: 'sup_004',
    variants: [
      { id: 'var_010a', name: 'Silky Smooth', priceAdjustment: 0 },
      { id: 'var_010b', name: 'Anti-Dandruff', priceAdjustment: 5 },
    ],
    costPrice: 65,
    wholesalePrice: 78,
    retailPrice: 89,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_011',
    sku: 'COLGATE-150G',
    name: 'Colgate Toothpaste',
    description: 'Cavity protection',
    categoryId: 'cat_004',
    supplierId: 'sup_004',
    variants: [],
    costPrice: 55,
    wholesalePrice: 65,
    retailPrice: 75,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  // Household
  {
    id: 'prod_012',
    sku: 'TIDE-1KG',
    name: 'Tide Detergent',
    description: 'Powerful stain remover',
    categoryId: 'cat_005',
    supplierId: 'sup_004',
    variants: [
      { id: 'var_012a', name: 'Original', priceAdjustment: 0 },
      { id: 'var_012b', name: 'With Downy', priceAdjustment: 15 },
    ],
    costPrice: 110,
    wholesalePrice: 128,
    retailPrice: 145,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_013',
    sku: 'JOY-250ML',
    name: 'Joy Dishwashing Liquid',
    description: 'Effective grease remover',
    categoryId: 'cat_005',
    supplierId: 'sup_004',
    variants: [
      { id: 'var_013a', name: 'Lemon', priceAdjustment: 0 },
      { id: 'var_013b', name: 'Antibac', priceAdjustment: 5 },
    ],
    costPrice: 48,
    wholesalePrice: 56,
    retailPrice: 65,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  // Rice & Grains
  {
    id: 'prod_014',
    sku: 'JASMINE-5KG',
    name: 'Jasmine Rice',
    description: 'Premium quality rice',
    categoryId: 'cat_006',
    supplierId: 'sup_002',
    variants: [],
    costPrice: 280,
    wholesalePrice: 320,
    retailPrice: 350,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_015',
    sku: 'LUCKY-55G',
    name: 'Lucky Me Pancit Canton',
    description: 'Instant noodles',
    categoryId: 'cat_006',
    supplierId: 'sup_003',
    variants: [
      { id: 'var_015a', name: 'Original', priceAdjustment: 0 },
      { id: 'var_015b', name: 'Chilimansi', priceAdjustment: 0 },
      { id: 'var_015c', name: 'Sweet & Spicy', priceAdjustment: 0 },
    ],
    costPrice: 10,
    wholesalePrice: 12,
    retailPrice: 14,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  // Condiments
  {
    id: 'prod_016',
    sku: 'DATU-350ML',
    name: 'Datu Puti Soy Sauce',
    description: 'Classic soy sauce',
    categoryId: 'cat_007',
    supplierId: 'sup_002',
    variants: [],
    costPrice: 28,
    wholesalePrice: 33,
    retailPrice: 38,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_017',
    sku: 'UFC-320G',
    name: 'UFC Banana Ketchup',
    description: 'Sweet banana ketchup',
    categoryId: 'cat_007',
    supplierId: 'sup_002',
    variants: [],
    costPrice: 32,
    wholesalePrice: 39,
    retailPrice: 45,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  // Dairy
  {
    id: 'prod_018',
    sku: 'BEAR-150ML',
    name: 'Bear Brand Milk',
    description: 'Sterilized milk',
    categoryId: 'cat_008',
    supplierId: 'sup_001',
    variants: [],
    costPrice: 20,
    wholesalePrice: 24,
    retailPrice: 28,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_019',
    sku: 'ALASKA-370ML',
    name: 'Alaska Evaporated Milk',
    description: 'Evaporated filled milk',
    categoryId: 'cat_008',
    supplierId: 'sup_001',
    variants: [],
    costPrice: 38,
    wholesalePrice: 45,
    retailPrice: 52,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod_020',
    sku: 'EDEN-165G',
    name: 'Eden Cheese',
    description: 'Filled cheese spread',
    categoryId: 'cat_008',
    supplierId: 'sup_001',
    variants: [],
    costPrice: 45,
    wholesalePrice: 54,
    retailPrice: 62,
    images: [],
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
]

// Three-tier inventory levels
export const mockInventoryLevels: InventoryLevel[] = [
  {
    id: 'inv_001',
    productId: 'prod_001',
    wholesaleQty: 10,
    retailQty: 24,
    shelfQty: 48,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 12,
    packsPerBox: 4,
    reorderLevel: 20,
    updatedAt: new Date(),
  },
  {
    id: 'inv_002',
    productId: 'prod_002',
    wholesaleQty: 8,
    retailQty: 20,
    shelfQty: 35,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 12,
    packsPerBox: 4,
    reorderLevel: 15,
    updatedAt: new Date(),
  },
  {
    id: 'inv_003',
    productId: 'prod_003',
    wholesaleQty: 15,
    retailQty: 30,
    shelfQty: 72,
    wholesaleUnit: 'case',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 30,
    updatedAt: new Date(),
  },
  {
    id: 'inv_004',
    productId: 'prod_004',
    wholesaleQty: 12,
    retailQty: 24,
    shelfQty: 60,
    wholesaleUnit: 'case',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 25,
    updatedAt: new Date(),
  },
  {
    id: 'inv_005',
    productId: 'prod_005',
    wholesaleQty: 8,
    retailQty: 16,
    shelfQty: 42,
    wholesaleUnit: 'case',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 20,
    updatedAt: new Date(),
  },
  {
    id: 'inv_006',
    productId: 'prod_006',
    wholesaleQty: 5,
    retailQty: 10,
    shelfQty: 8, // Low stock
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 1,
    packsPerBox: 24,
    reorderLevel: 15,
    updatedAt: new Date(),
  },
  {
    id: 'inv_007',
    productId: 'prod_007',
    wholesaleQty: 6,
    retailQty: 12,
    shelfQty: 18,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 1,
    packsPerBox: 24,
    reorderLevel: 12,
    updatedAt: new Date(),
  },
  {
    id: 'inv_008',
    productId: 'prod_008',
    wholesaleQty: 20,
    retailQty: 50,
    shelfQty: 100,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 10,
    packsPerBox: 10,
    reorderLevel: 50,
    updatedAt: new Date(),
  },
  {
    id: 'inv_009',
    productId: 'prod_009',
    wholesaleQty: 4,
    retailQty: 8,
    shelfQty: 5, // Low stock
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 6,
    reorderLevel: 12,
    updatedAt: new Date(),
  },
  {
    id: 'inv_010',
    productId: 'prod_010',
    wholesaleQty: 3,
    retailQty: 6,
    shelfQty: 12,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 10,
    updatedAt: new Date(),
  },
  {
    id: 'inv_011',
    productId: 'prod_011',
    wholesaleQty: 5,
    retailQty: 10,
    shelfQty: 0, // Out of stock
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 8,
    updatedAt: new Date(),
  },
  {
    id: 'inv_012',
    productId: 'prod_012',
    wholesaleQty: 8,
    retailQty: 16,
    shelfQty: 24,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 15,
    updatedAt: new Date(),
  },
  {
    id: 'inv_013',
    productId: 'prod_013',
    wholesaleQty: 6,
    retailQty: 12,
    shelfQty: 18,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 10,
    updatedAt: new Date(),
  },
  {
    id: 'inv_014',
    productId: 'prod_014',
    wholesaleQty: 20,
    retailQty: 0,
    shelfQty: 15,
    wholesaleUnit: 'sack',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 1,
    packsPerBox: 1,
    reorderLevel: 10,
    updatedAt: new Date(),
  },
  {
    id: 'inv_015',
    productId: 'prod_015',
    wholesaleQty: 30,
    retailQty: 60,
    shelfQty: 120,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 10,
    reorderLevel: 50,
    updatedAt: new Date(),
  },
  {
    id: 'inv_016',
    productId: 'prod_016',
    wholesaleQty: 10,
    retailQty: 20,
    shelfQty: 30,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 15,
    updatedAt: new Date(),
  },
  {
    id: 'inv_017',
    productId: 'prod_017',
    wholesaleQty: 8,
    retailQty: 16,
    shelfQty: 25,
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 12,
    updatedAt: new Date(),
  },
  {
    id: 'inv_018',
    productId: 'prod_018',
    wholesaleQty: 15,
    retailQty: 30,
    shelfQty: 48,
    wholesaleUnit: 'case',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 25,
    updatedAt: new Date(),
  },
  {
    id: 'inv_019',
    productId: 'prod_019',
    wholesaleQty: 10,
    retailQty: 20,
    shelfQty: 35,
    wholesaleUnit: 'case',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 18,
    updatedAt: new Date(),
  },
  {
    id: 'inv_020',
    productId: 'prod_020',
    wholesaleQty: 6,
    retailQty: 12,
    shelfQty: 3, // Low stock
    wholesaleUnit: 'box',
    retailUnit: 'pack',
    shelfUnit: 'pack',
    pcsPerPack: 6,
    packsPerBox: 4,
    reorderLevel: 10,
    updatedAt: new Date(),
  },
]

export function getProductById(id: string): Product | undefined {
  return mockProducts.find(prod => prod.id === id)
}

export function getProductInventory(productId: string): InventoryLevel | undefined {
  return mockInventoryLevels.find(inv => inv.productId === productId)
}

export function getLowStockProducts(): { product: Product; inventory: InventoryLevel }[] {
  return mockInventoryLevels
    .filter(inv => inv.shelfQty <= inv.reorderLevel)
    .map(inv => ({
      product: getProductById(inv.productId)!,
      inventory: inv,
    }))
    .filter(item => item.product)
}

export function getOutOfStockProducts(): { product: Product; inventory: InventoryLevel }[] {
  return mockInventoryLevels
    .filter(inv => inv.shelfQty === 0)
    .map(inv => ({
      product: getProductById(inv.productId)!,
      inventory: inv,
    }))
    .filter(item => item.product)
}
